version: '3'

services:
  orc_server_hangover:
    build: .
    restart: always
    user: 1001:1001
    working_dir: /home/user/orc_server
    environment:
      - HODLL=xtajit.dll
    network_mode: "host"
    command: ./run.sh